-- Run this once in Supabase Dashboard -> SQL Editor for the alex.fun project.
-- This version uses game-only usernames/passwords. No email addresses are used.
-- It stores password hashes with pgcrypto and gives the browser a random session token.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;


-- If you previously ran the email/Auth version of this setup, those old tables have
-- different columns. This resets only the alex.fun game tables so the no-email
-- username/password version can be installed cleanly.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'clicker_saves' and column_name = 'user_id'
  ) then
    drop table if exists public.clicker_saves cascade;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'suggestions' and column_name = 'user_id'
  ) then
    drop table if exists public.suggestions cascade;
  end if;
end $$;

create table if not exists public.players (
  id uuid primary key default extensions.gen_random_uuid(),
  username text not null unique,
  password_hash text not null,
  banned_at timestamptz,
  ban_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.players add column if not exists banned_at timestamptz;
alter table public.players add column if not exists ban_reason text;

create table if not exists public.player_sessions (
  token text primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '180 days'
);

create table if not exists public.clicker_saves (
  player_id uuid primary key references public.players(id) on delete cascade,
  save jsonb not null default '{}'::jsonb,
  max_points numeric not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.infinite_craft_saves (
  player_id uuid primary key references public.players(id) on delete cascade,
  discoveries jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.suggestions (
  id bigint generated by default as identity primary key,
  player_id uuid references public.players(id) on delete set null,
  username text,
  idea text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.recipe_cache (
  recipe_key text primary key,
  input_a text not null,
  input_b text not null,
  result_emoji text,
  result_name text,
  missing boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_actions (
  id bigint generated by default as identity primary key,
  admin_player_id uuid references public.players(id) on delete set null,
  target_player_id uuid references public.players(id) on delete set null,
  target_username text not null,
  action text not null,
  reason text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.game_updates (
  id text primary key,
  applied_at timestamptz not null default now()
);

alter table public.players enable row level security;
alter table public.player_sessions enable row level security;
alter table public.clicker_saves enable row level security;
alter table public.infinite_craft_saves enable row level security;
alter table public.suggestions enable row level security;
alter table public.recipe_cache enable row level security;
alter table public.admin_actions enable row level security;
alter table public.game_updates enable row level security;

create or replace function public.normalize_player_username(p_username text)
returns text
language sql
immutable
as $$
  select lower(regexp_replace(trim(coalesce(p_username, '')), '[^a-z0-9_-]', '', 'g'));
$$;

create or replace function public.player_id_from_token(p_token text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid;
begin
  select player_id into v_player_id
  from public.player_sessions
  where token = p_token and expires_at > now();

  if v_player_id is null then
    raise exception 'Invalid or expired session';
  end if;

  return v_player_id;
end;
$$;

create or replace function public.register_player(p_username text, p_password text)
returns table(session_token text, player_id uuid, username text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text := public.normalize_player_username(p_username);
  v_player_id uuid;
  v_token text;
begin
  if length(v_username) < 3 then
    raise exception 'Username must be at least 3 letters or numbers';
  end if;

  if length(coalesce(p_password, '')) < 6 then
    raise exception 'Password must be at least 6 characters';
  end if;

  insert into public.players(username, password_hash)
  values (v_username, extensions.crypt(p_password, extensions.gen_salt('bf')))
  returning id into v_player_id;

  v_token := encode(extensions.gen_random_bytes(32), 'hex');
  insert into public.player_sessions(token, player_id) values (v_token, v_player_id);

  return query select v_token, v_player_id, v_username;
exception
  when unique_violation then
    raise exception 'That username already exists';
end;
$$;

create or replace function public.login_player(p_username text, p_password text)
returns table(session_token text, player_id uuid, username text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text := public.normalize_player_username(p_username);
  v_player record;
  v_token text;
begin
  select p.id, p.username, p.password_hash, p.banned_at, p.ban_reason into v_player
  from public.players p
  where p.username = v_username;

  if v_player.id is null or v_player.password_hash <> extensions.crypt(p_password, v_player.password_hash) then
    raise exception 'Wrong username or password';
  end if;

  if v_player.banned_at is not null then
    raise exception 'This account is banned: %', coalesce(v_player.ban_reason, 'No reason provided');
  end if;

  v_token := encode(extensions.gen_random_bytes(32), 'hex');
  insert into public.player_sessions(token, player_id) values (v_token, v_player.id);

  return query select v_token, v_player.id, v_player.username;
end;
$$;

create or replace function public.get_clicker_save(p_token text)
returns table(username text, save jsonb, max_points numeric, updated_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
begin
  return query
  select p.username, s.save, coalesce(s.max_points, 0), s.updated_at
  from public.players p
  left join public.clicker_saves s on s.player_id = p.id
  where p.id = v_player_id;
end;
$$;

create or replace function public.save_clicker(p_token text, p_save jsonb, p_max_points numeric)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
begin
  insert into public.clicker_saves(player_id, save, max_points, updated_at)
  values (v_player_id, coalesce(p_save, '{}'::jsonb), greatest(coalesce(p_max_points, 0), 0), now())
  on conflict (player_id) do update set
    save = excluded.save,
    max_points = greatest(public.clicker_saves.max_points, excluded.max_points),
    updated_at = now();
end;
$$;

create or replace function public.delete_clicker_save(p_token text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
begin
  delete from public.clicker_saves where player_id = v_player_id;
end;
$$;

create or replace function public.require_alex_admin(p_token text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
  v_username text;
begin
  select username into v_username from public.players where id = v_player_id;
  if v_username <> 'alex' then
    raise exception 'Admin access denied';
  end if;
  return v_player_id;
end;
$$;

create or replace function public.list_public_players(p_token text default '')
returns table(username text, created_at timestamptz)
language sql
security definer
set search_path = public
as $$
  select p.username, p.created_at
  from public.players p
  where p.banned_at is null
  order by p.username
  limit 250;
$$;

create or replace function public.admin_ban_player(p_token text, p_target_username text, p_reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_id uuid := public.require_alex_admin(p_token);
  v_target_username text := public.normalize_player_username(p_target_username);
  v_target_id uuid;
begin
  if length(trim(coalesce(p_reason, ''))) < 3 then
    raise exception 'A ban reason is required';
  end if;

  select id into v_target_id from public.players where username = v_target_username;
  if v_target_id is null then
    raise exception 'Target user not found';
  end if;

  update public.players
  set banned_at = now(), ban_reason = trim(p_reason), updated_at = now()
  where id = v_target_id;

  delete from public.player_sessions where player_id = v_target_id;

  insert into public.admin_actions(admin_player_id, target_player_id, target_username, action, reason)
  values (v_admin_id, v_target_id, v_target_username, 'ban', trim(p_reason));
end;
$$;

create or replace function public.admin_wipe_player(p_token text, p_target_username text, p_reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_id uuid := public.require_alex_admin(p_token);
  v_target_username text := public.normalize_player_username(p_target_username);
  v_target_id uuid;
begin
  if length(trim(coalesce(p_reason, ''))) < 3 then
    raise exception 'A wipe reason is required';
  end if;

  select id into v_target_id from public.players where username = v_target_username;
  if v_target_id is null then
    raise exception 'Target user not found';
  end if;

  delete from public.clicker_saves where player_id = v_target_id;
  delete from public.infinite_craft_saves where player_id = v_target_id;

  insert into public.admin_actions(admin_player_id, target_player_id, target_username, action, reason)
  values (v_admin_id, v_target_id, v_target_username, 'wipe', trim(p_reason));
end;
$$;

create or replace function public.get_infinite_craft_save(p_token text)
returns table(username text, discoveries jsonb, updated_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
begin
  return query
  select p.username, coalesce(s.discoveries, '[]'::jsonb), s.updated_at
  from public.players p
  left join public.infinite_craft_saves s on s.player_id = p.id
  where p.id = v_player_id;
end;
$$;

create or replace function public.save_infinite_craft(p_token text, p_discoveries jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
  v_discoveries jsonb := coalesce(p_discoveries, '[]'::jsonb);
begin
  if jsonb_typeof(v_discoveries) <> 'array' then
    raise exception 'Discoveries must be a JSON array';
  end if;

  insert into public.infinite_craft_saves(player_id, discoveries, updated_at)
  values (v_player_id, v_discoveries, now())
  on conflict (player_id) do update set
    discoveries = excluded.discoveries,
    updated_at = now();
end;
$$;

create or replace function public.delete_infinite_craft_save(p_token text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
begin
  delete from public.infinite_craft_saves where player_id = v_player_id;
end;
$$;

create or replace function public.get_clicker_leaderboard()
returns table(username text, max_points numeric, updated_at timestamptz)
language sql
security definer
set search_path = public
as $$
  select p.username, s.max_points, s.updated_at
  from public.clicker_saves s
  join public.players p on p.id = s.player_id
  order by s.max_points desc
  limit 10;
$$;

create or replace function public.submit_suggestion(p_token text, p_idea text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid;
  v_username text;
begin
  if length(trim(coalesce(p_idea, ''))) < 2 then
    return;
  end if;

  if p_token is not null and p_token <> '' then
    v_player_id := public.player_id_from_token(p_token);
    select username into v_username from public.players where id = v_player_id;
  end if;

  insert into public.suggestions(player_id, username, idea)
  values (v_player_id, v_username, trim(p_idea));
end;
$$;

-- Only recipe cache is directly public because it is not private user data.
drop policy if exists "recipe cache is readable" on public.recipe_cache;
drop policy if exists "recipe cache can be filled by site users" on public.recipe_cache;
drop policy if exists "recipe cache can be updated by site users" on public.recipe_cache;
create policy "recipe cache is readable" on public.recipe_cache for select using (true);
create policy "recipe cache can be filled by site users" on public.recipe_cache for insert with check (true);
create policy "recipe cache can be updated by site users" on public.recipe_cache for update using (true) with check (true);

revoke all on public.players from anon, authenticated;
revoke all on public.player_sessions from anon, authenticated;
revoke all on public.clicker_saves from anon, authenticated;
revoke all on public.infinite_craft_saves from anon, authenticated;
revoke all on public.suggestions from anon, authenticated;
revoke all on public.admin_actions from anon, authenticated;
revoke all on public.game_updates from anon, authenticated;
grant select, insert, update on public.recipe_cache to anon, authenticated;
grant execute on function public.register_player(text, text) to anon, authenticated;
grant execute on function public.login_player(text, text) to anon, authenticated;
grant execute on function public.get_clicker_save(text) to anon, authenticated;
grant execute on function public.save_clicker(text, jsonb, numeric) to anon, authenticated;
grant execute on function public.delete_clicker_save(text) to anon, authenticated;
grant execute on function public.require_alex_admin(text) to anon, authenticated;
grant execute on function public.list_public_players(text) to anon, authenticated;
grant execute on function public.admin_ban_player(text, text, text) to anon, authenticated;
grant execute on function public.admin_wipe_player(text, text, text) to anon, authenticated;
grant execute on function public.get_infinite_craft_save(text) to anon, authenticated;
grant execute on function public.save_infinite_craft(text, jsonb) to anon, authenticated;
grant execute on function public.delete_infinite_craft_save(text) to anon, authenticated;
grant execute on function public.get_clicker_leaderboard() to anon, authenticated;
grant execute on function public.submit_suggestion(text, text) to anon, authenticated;

with applied_update as (
  insert into public.game_updates(id)
  values ('67-balance-2026-05-13')
  on conflict (id) do nothing
  returning id
)
delete from public.clicker_saves
where exists (select 1 from applied_update);

create index if not exists player_sessions_player_id_idx on public.player_sessions (player_id);
create index if not exists player_sessions_expires_at_idx on public.player_sessions (expires_at);
create index if not exists clicker_saves_max_points_idx on public.clicker_saves (max_points desc);
create index if not exists infinite_craft_saves_updated_at_idx on public.infinite_craft_saves (updated_at desc);
create index if not exists recipe_cache_updated_at_idx on public.recipe_cache (updated_at desc);
create index if not exists players_banned_at_idx on public.players (banned_at);
create index if not exists admin_actions_created_at_idx on public.admin_actions (created_at desc);

-- Make newly-created RPC functions visible to the browser API immediately.
notify pgrst, 'reload schema';
