-- Run this once in Supabase Dashboard -> SQL Editor for the alex.fun project.
-- This version uses game-only usernames/passwords. No email addresses are used.
-- It stores password hashes with pgcrypto and gives the browser a random session token.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;


-- If you previously ran the email/Auth version of this setup, those old tables have
-- different columns. This resets only the alex.fun game tables so the no-email
-- username/password version can be installed cleanly.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'clicker_saves' and column_name = 'user_id'
  ) then
    drop table if exists public.clicker_saves cascade;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'suggestions' and column_name = 'user_id'
  ) then
    drop table if exists public.suggestions cascade;
  end if;
end $$;

create table if not exists public.players (
  id uuid primary key default extensions.gen_random_uuid(),
  username text not null unique,
  password_hash text not null,
  banned_at timestamptz,
  ban_reason text,
  ban_expires_at timestamptz,
  delete_requested_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.players add column if not exists banned_at timestamptz;
alter table public.players add column if not exists ban_reason text;
alter table public.players add column if not exists ban_expires_at timestamptz;
alter table public.players add column if not exists delete_requested_at timestamptz;

create table if not exists public.player_sessions (
  token text primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '180 days'
);

create table if not exists public.clicker_saves (
  player_id uuid primary key references public.players(id) on delete cascade,
  save jsonb not null default '{}'::jsonb,
  max_points numeric not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.infinite_craft_saves (
  player_id uuid primary key references public.players(id) on delete cascade,
  discoveries jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.suggestions (
  id bigint generated by default as identity primary key,
  player_id uuid references public.players(id) on delete set null,
  username text,
  idea text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.recipe_cache (
  recipe_key text primary key,
  input_a text not null,
  input_b text not null,
  result_emoji text,
  result_name text,
  missing boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_actions (
  id bigint generated by default as identity primary key,
  admin_player_id uuid references public.players(id) on delete set null,
  target_player_id uuid references public.players(id) on delete set null,
  target_username text not null,
  action text not null,
  reason text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.game_updates (
  id text primary key,
  applied_at timestamptz not null default now()
);

create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.players(id) on delete cascade,
  recipient_id uuid not null references public.players(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(requester_id, recipient_id)
);

create table if not exists public.friendships (
  player_a uuid not null references public.players(id) on delete cascade,
  player_b uuid not null references public.players(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(player_a, player_b),
  check(player_a <> player_b)
);

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.players(id) on delete cascade,
  recipient_id uuid not null references public.players(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  actor_id uuid references public.players(id) on delete set null,
  actor_username text,
  kind text not null,
  body text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create table if not exists public.ban_appeals (
  id bigint generated by default as identity primary key,
  player_id uuid references public.players(id) on delete set null,
  username text not null,
  message text not null,
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.players enable row level security;
alter table public.player_sessions enable row level security;
alter table public.clicker_saves enable row level security;
alter table public.infinite_craft_saves enable row level security;
alter table public.suggestions enable row level security;
alter table public.recipe_cache enable row level security;
alter table public.admin_actions enable row level security;
alter table public.game_updates enable row level security;
alter table public.friend_requests enable row level security;
alter table public.friendships enable row level security;
alter table public.direct_messages enable row level security;
alter table public.notifications enable row level security;
alter table public.ban_appeals enable row level security;

create or replace function public.normalize_player_username(p_username text)
returns text
language sql
immutable
as $$
  select lower(regexp_replace(trim(coalesce(p_username, '')), '[^a-z0-9_-]', '', 'g'));
$$;

create or replace function public.player_id_from_token(p_token text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid;
  v_player record;
begin
  select player_id into v_player_id
  from public.player_sessions
  where token = p_token and expires_at > now();

  if v_player_id is null then
    raise exception 'Invalid or expired session';
  end if;

  select id, banned_at, ban_expires_at, ban_reason into v_player
  from public.players
  where id = v_player_id;

  if v_player.banned_at is not null and (v_player.ban_expires_at is null or v_player.ban_expires_at > now()) then
    delete from public.player_sessions where player_id = v_player_id;
    raise exception 'This account is banned: %', coalesce(v_player.ban_reason, 'No reason provided');
  elsif v_player.banned_at is not null and v_player.ban_expires_at <= now() then
    update public.players
    set banned_at = null, ban_reason = null, ban_expires_at = null, updated_at = now()
    where id = v_player_id;
  end if;

  return v_player_id;
end;
$$;

create or replace function public.register_player(p_username text, p_password text)
returns table(session_token text, player_id uuid, username text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text := public.normalize_player_username(p_username);
  v_player_id uuid;
  v_token text;
begin
  if length(v_username) < 3 then
    raise exception 'Username must be at least 3 letters or numbers';
  end if;

  if length(coalesce(p_password, '')) < 6 then
    raise exception 'Password must be at least 6 characters';
  end if;

  insert into public.players(username, password_hash)
  values (v_username, extensions.crypt(p_password, extensions.gen_salt('bf')))
  returning id into v_player_id;

  v_token := encode(extensions.gen_random_bytes(32), 'hex');
  insert into public.player_sessions(token, player_id) values (v_token, v_player_id);

  return query select v_token, v_player_id, v_username;
exception
  when unique_violation then
    raise exception 'That username already exists';
end;
$$;

create or replace function public.login_player(p_username text, p_password text)
returns table(session_token text, player_id uuid, username text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text := public.normalize_player_username(p_username);
  v_player record;
  v_token text;
begin
  select p.id, p.username, p.password_hash, p.banned_at, p.ban_reason, p.ban_expires_at into v_player
  from public.players p
  where p.username = v_username;

  if v_player.id is null or v_player.password_hash <> extensions.crypt(p_password, v_player.password_hash) then
    raise exception 'Wrong username or password';
  end if;

  if v_player.banned_at is not null and (v_player.ban_expires_at is null or v_player.ban_expires_at > now()) then
    raise exception 'This account is banned: %', coalesce(v_player.ban_reason, 'No reason provided');
  elsif v_player.banned_at is not null and v_player.ban_expires_at <= now() then
    update public.players
    set banned_at = null, ban_reason = null, ban_expires_at = null, updated_at = now()
    where id = v_player.id;
  end if;

  v_token := encode(extensions.gen_random_bytes(32), 'hex');
  insert into public.player_sessions(token, player_id) values (v_token, v_player.id);

  return query select v_token, v_player.id, v_player.username;
end;
$$;

create or replace function public.get_ban_status(p_username text)
returns table(username text, banned boolean, reason text, banned_at timestamptz, ban_expires_at timestamptz, remaining_seconds bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text := public.normalize_player_username(p_username);
  v_player record;
begin
  select p.username, p.banned_at, p.ban_reason, p.ban_expires_at into v_player
  from public.players p
  where p.username = v_username;

  if v_player.username is null then
    return query select v_username, false, null::text, null::timestamptz, null::timestamptz, null::bigint;
    return;
  end if;

  if v_player.banned_at is not null and v_player.ban_expires_at is not null and v_player.ban_expires_at <= now() then
    update public.players
    set banned_at = null, ban_reason = null, ban_expires_at = null, updated_at = now()
    where public.players.username = v_username;
    return query select v_username, false, null::text, null::timestamptz, null::timestamptz, null::bigint;
    return;
  end if;

  return query select
    v_player.username,
    v_player.banned_at is not null,
    v_player.ban_reason,
    v_player.banned_at,
    v_player.ban_expires_at,
    case
      when v_player.banned_at is null then null::bigint
      when v_player.ban_expires_at is null then null::bigint
      else greatest(0, floor(extract(epoch from (v_player.ban_expires_at - now())))::bigint)
    end;
end;
$$;

create or replace function public.get_clicker_save(p_token text)
returns table(username text, save jsonb, max_points numeric, updated_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
begin
  return query
  select p.username, s.save, coalesce(s.max_points, 0), s.updated_at
  from public.players p
  left join public.clicker_saves s on s.player_id = p.id
  where p.id = v_player_id;
end;
$$;

create or replace function public.save_clicker(p_token text, p_save jsonb, p_max_points numeric)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
begin
  insert into public.clicker_saves(player_id, save, max_points, updated_at)
  values (v_player_id, coalesce(p_save, '{}'::jsonb), greatest(coalesce(p_max_points, 0), 0), now())
  on conflict (player_id) do update set
    save = excluded.save,
    max_points = greatest(public.clicker_saves.max_points, excluded.max_points),
    updated_at = now();
end;
$$;

create or replace function public.delete_clicker_save(p_token text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
begin
  delete from public.clicker_saves where player_id = v_player_id;
end;
$$;

create or replace function public.require_alex_admin(p_token text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
  v_username text;
begin
  select username into v_username from public.players where id = v_player_id;
  if v_username <> 'alex' then
    raise exception 'Admin access denied';
  end if;
  return v_player_id;
end;
$$;

create or replace function public.list_public_players(p_token text default '')
returns table(username text, created_at timestamptz)
language sql
security definer
set search_path = public
as $$
  select p.username, p.created_at
  from public.players p
  where p.banned_at is null
  order by p.username
  limit 250;
$$;

create or replace function public.admin_ban_player(p_token text, p_target_username text, p_reason text, p_duration_minutes integer default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_id uuid := public.require_alex_admin(p_token);
  v_target_username text := public.normalize_player_username(p_target_username);
  v_target_id uuid;
  v_expires_at timestamptz;
begin
  if length(trim(coalesce(p_reason, ''))) < 3 then
    raise exception 'A ban reason is required';
  end if;

  if p_duration_minutes is not null and p_duration_minutes > 0 then
    v_expires_at := now() + make_interval(mins => p_duration_minutes);
  end if;

  select id into v_target_id from public.players where username = v_target_username;
  if v_target_id is null then
    raise exception 'Target user not found';
  end if;

  update public.players
  set banned_at = now(), ban_reason = trim(p_reason), ban_expires_at = v_expires_at, updated_at = now()
  where id = v_target_id;

  delete from public.player_sessions where player_id = v_target_id;

  insert into public.admin_actions(admin_player_id, target_player_id, target_username, action, reason)
  values (v_admin_id, v_target_id, v_target_username, 'ban', trim(p_reason) || coalesce(' (' || p_duration_minutes || ' minutes)', ' (permanent)'));
end;
$$;

create or replace function public.admin_ban_player(p_token text, p_target_username text, p_reason text)
returns void
language sql
security definer
set search_path = public
as $$
  select public.admin_ban_player(p_token, p_target_username, p_reason, null::integer);
$$;

create or replace function public.admin_unban_player(p_token text, p_target_username text, p_reason text default 'manual unban')
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_id uuid := public.require_alex_admin(p_token);
  v_target_username text := public.normalize_player_username(p_target_username);
  v_target_id uuid;
begin
  select id into v_target_id from public.players where username = v_target_username;
  if v_target_id is null then
    raise exception 'Target user not found';
  end if;

  update public.players
  set banned_at = null, ban_reason = null, ban_expires_at = null, updated_at = now()
  where id = v_target_id;

  insert into public.admin_actions(admin_player_id, target_player_id, target_username, action, reason)
  values (v_admin_id, v_target_id, v_target_username, 'unban', trim(coalesce(p_reason, 'manual unban')));
end;
$$;

create or replace function public.admin_wipe_player(p_token text, p_target_username text, p_reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_id uuid := public.require_alex_admin(p_token);
  v_target_username text := public.normalize_player_username(p_target_username);
  v_target_id uuid;
begin
  if length(trim(coalesce(p_reason, ''))) < 3 then
    raise exception 'A wipe reason is required';
  end if;

  select id into v_target_id from public.players where username = v_target_username;
  if v_target_id is null then
    raise exception 'Target user not found';
  end if;

  delete from public.clicker_saves where player_id = v_target_id;
  delete from public.infinite_craft_saves where player_id = v_target_id;

  insert into public.admin_actions(admin_player_id, target_player_id, target_username, action, reason)
  values (v_admin_id, v_target_id, v_target_username, 'wipe', trim(p_reason));
end;
$$;

create or replace function public.submit_ban_appeal(p_username text, p_message text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text := public.normalize_player_username(p_username);
  v_player_id uuid;
begin
  if length(trim(coalesce(p_message, ''))) < 5 then
    raise exception 'Appeal message must be at least 5 characters';
  end if;
  select id into v_player_id from public.players where username = v_username;
  insert into public.ban_appeals(player_id, username, message)
  values (v_player_id, v_username, trim(p_message));
end;
$$;

create or replace function public.delete_player_account(p_username text, p_password text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text := public.normalize_player_username(p_username);
  v_player record;
begin
  select id, password_hash into v_player from public.players where username = v_username;
  if v_player.id is null or v_player.password_hash <> extensions.crypt(p_password, v_player.password_hash) then
    raise exception 'Wrong username or password';
  end if;
  delete from public.players where id = v_player.id;
end;
$$;

create or replace function public.send_friend_request(p_token text, p_target_username text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
  v_actor_username text;
  v_target_username text := public.normalize_player_username(p_target_username);
  v_target_id uuid;
begin
  select username into v_actor_username from public.players where id = v_player_id;
  select id into v_target_id from public.players where username = v_target_username and banned_at is null;
  if v_target_id is null then raise exception 'User not found'; end if;
  if v_target_id = v_player_id then raise exception 'You cannot friend yourself'; end if;

  insert into public.friend_requests(requester_id, recipient_id, status, updated_at)
  values (v_player_id, v_target_id, 'pending', now())
  on conflict (requester_id, recipient_id) do update set status = 'pending', updated_at = now();

  insert into public.notifications(player_id, actor_id, actor_username, kind, body)
  values (v_target_id, v_player_id, v_actor_username, 'friend_request', v_actor_username || ' sent you a friend request');
end;
$$;

create or replace function public.respond_friend_request(p_token text, p_request_id bigint, p_accept boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
  v_request record;
  v_actor_username text;
  v_low uuid;
  v_high uuid;
begin
  select fr.*, p.username requester_username into v_request
  from public.friend_requests fr
  join public.players p on p.id = fr.requester_id
  where fr.id = p_request_id and fr.recipient_id = v_player_id and fr.status = 'pending';
  if v_request.id is null then raise exception 'Friend request not found'; end if;
  select username into v_actor_username from public.players where id = v_player_id;

  update public.friend_requests
  set status = case when p_accept then 'accepted' else 'declined' end, updated_at = now()
  where id = p_request_id;

  if p_accept then
    v_low := least(v_player_id, v_request.requester_id);
    v_high := greatest(v_player_id, v_request.requester_id);
    insert into public.friendships(player_a, player_b)
    values (v_low, v_high)
    on conflict do nothing;
    insert into public.notifications(player_id, actor_id, actor_username, kind, body)
    values (v_request.requester_id, v_player_id, v_actor_username, 'friend_accept', v_actor_username || ' accepted your friend request');
  end if;
end;
$$;

create or replace function public.send_direct_message(p_token text, p_recipient_username text, p_body text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
  v_actor_username text;
  v_recipient_username text := public.normalize_player_username(p_recipient_username);
  v_recipient_id uuid;
  v_body text := trim(coalesce(p_body, ''));
begin
  if length(v_body) < 1 then return; end if;
  if length(v_body) > 1000 then raise exception 'Message is too long'; end if;
  select username into v_actor_username from public.players where id = v_player_id;
  select id into v_recipient_id from public.players where username = v_recipient_username and banned_at is null;
  if v_recipient_id is null then raise exception 'Recipient not found'; end if;
  if v_recipient_id = v_player_id then raise exception 'You cannot message yourself'; end if;

  insert into public.direct_messages(sender_id, recipient_id, body)
  values (v_player_id, v_recipient_id, v_body);
  insert into public.notifications(player_id, actor_id, actor_username, kind, body)
  values (v_recipient_id, v_player_id, v_actor_username, 'message', 'New message from ' || v_actor_username);
end;
$$;

create or replace function public.mark_notifications_read(p_token text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
begin
  update public.notifications set read_at = now() where player_id = v_player_id and read_at is null;
  update public.direct_messages set read_at = now() where recipient_id = v_player_id and read_at is null;
end;
$$;

create or replace function public.list_social_state(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
  v_state jsonb;
begin
  select jsonb_build_object(
    'users', (
      select coalesce(jsonb_agg(username order by username), '[]'::jsonb)
      from public.players
      where banned_at is null
    ),
    'friends', (
      select coalesce(jsonb_agg(friend_username order by friend_username), '[]'::jsonb)
      from (
        select case when f.player_a = v_player_id then pb.username else pa.username end friend_username
        from public.friendships f
        join public.players pa on pa.id = f.player_a
        join public.players pb on pb.id = f.player_b
        where f.player_a = v_player_id or f.player_b = v_player_id
      ) friend_rows
    ),
    'incomingRequests', (
      select coalesce(jsonb_agg(jsonb_build_object('id', fr.id, 'username', p.username, 'created_at', fr.created_at) order by fr.created_at desc), '[]'::jsonb)
      from public.friend_requests fr
      join public.players p on p.id = fr.requester_id
      where fr.recipient_id = v_player_id and fr.status = 'pending'
    ),
    'outgoingRequests', (
      select coalesce(jsonb_agg(p.username order by p.username), '[]'::jsonb)
      from public.friend_requests fr
      join public.players p on p.id = fr.recipient_id
      where fr.requester_id = v_player_id and fr.status = 'pending'
    ),
    'messages', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', m.id,
        'from', sp.username,
        'to', rp.username,
        'body', m.body,
        'created_at', m.created_at,
        'mine', m.sender_id = v_player_id,
        'read_at', m.read_at
      ) order by m.created_at), '[]'::jsonb)
      from public.direct_messages m
      join public.players sp on sp.id = m.sender_id
      join public.players rp on rp.id = m.recipient_id
      where m.sender_id = v_player_id or m.recipient_id = v_player_id
    ),
    'notifications', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', n.id,
        'kind', n.kind,
        'from', n.actor_username,
        'body', n.body,
        'created_at', n.created_at,
        'read_at', n.read_at
      ) order by n.created_at desc), '[]'::jsonb)
      from (
        select * from public.notifications
        where player_id = v_player_id
        order by created_at desc
        limit 30
      ) n
    )
  ) into v_state;
  return v_state;
end;
$$;

create or replace function public.get_infinite_craft_save(p_token text)
returns table(username text, discoveries jsonb, updated_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
begin
  return query
  select p.username, coalesce(s.discoveries, '[]'::jsonb), s.updated_at
  from public.players p
  left join public.infinite_craft_saves s on s.player_id = p.id
  where p.id = v_player_id;
end;
$$;

create or replace function public.save_infinite_craft(p_token text, p_discoveries jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
  v_discoveries jsonb := coalesce(p_discoveries, '[]'::jsonb);
begin
  if jsonb_typeof(v_discoveries) <> 'array' then
    raise exception 'Discoveries must be a JSON array';
  end if;

  insert into public.infinite_craft_saves(player_id, discoveries, updated_at)
  values (v_player_id, v_discoveries, now())
  on conflict (player_id) do update set
    discoveries = excluded.discoveries,
    updated_at = now();
end;
$$;

create or replace function public.delete_infinite_craft_save(p_token text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid := public.player_id_from_token(p_token);
begin
  delete from public.infinite_craft_saves where player_id = v_player_id;
end;
$$;

create or replace function public.get_clicker_leaderboard()
returns table(username text, max_points numeric, updated_at timestamptz)
language sql
security definer
set search_path = public
as $$
  select p.username, s.max_points, s.updated_at
  from public.clicker_saves s
  join public.players p on p.id = s.player_id
  order by s.max_points desc
  limit 10;
$$;

create or replace function public.submit_suggestion(p_token text, p_idea text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid;
  v_username text;
begin
  if length(trim(coalesce(p_idea, ''))) < 2 then
    return;
  end if;

  if p_token is not null and p_token <> '' then
    v_player_id := public.player_id_from_token(p_token);
    select username into v_username from public.players where id = v_player_id;
  end if;

  insert into public.suggestions(player_id, username, idea)
  values (v_player_id, v_username, trim(p_idea));
end;
$$;

-- Only recipe cache is directly public because it is not private user data.
drop policy if exists "recipe cache is readable" on public.recipe_cache;
drop policy if exists "recipe cache can be filled by site users" on public.recipe_cache;
drop policy if exists "recipe cache can be updated by site users" on public.recipe_cache;
create policy "recipe cache is readable" on public.recipe_cache for select using (true);
create policy "recipe cache can be filled by site users" on public.recipe_cache for insert with check (true);
create policy "recipe cache can be updated by site users" on public.recipe_cache for update using (true) with check (true);

revoke all on public.players from anon, authenticated;
revoke all on public.player_sessions from anon, authenticated;
revoke all on public.clicker_saves from anon, authenticated;
revoke all on public.infinite_craft_saves from anon, authenticated;
revoke all on public.suggestions from anon, authenticated;
revoke all on public.admin_actions from anon, authenticated;
revoke all on public.game_updates from anon, authenticated;
revoke all on public.friend_requests from anon, authenticated;
revoke all on public.friendships from anon, authenticated;
revoke all on public.direct_messages from anon, authenticated;
revoke all on public.notifications from anon, authenticated;
revoke all on public.ban_appeals from anon, authenticated;
grant select, insert, update on public.recipe_cache to anon, authenticated;
grant execute on function public.register_player(text, text) to anon, authenticated;
grant execute on function public.login_player(text, text) to anon, authenticated;
grant execute on function public.get_ban_status(text) to anon, authenticated;
grant execute on function public.get_clicker_save(text) to anon, authenticated;
grant execute on function public.save_clicker(text, jsonb, numeric) to anon, authenticated;
grant execute on function public.delete_clicker_save(text) to anon, authenticated;
grant execute on function public.require_alex_admin(text) to anon, authenticated;
grant execute on function public.list_public_players(text) to anon, authenticated;
grant execute on function public.admin_ban_player(text, text, text) to anon, authenticated;
grant execute on function public.admin_ban_player(text, text, text, integer) to anon, authenticated;
grant execute on function public.admin_unban_player(text, text, text) to anon, authenticated;
grant execute on function public.admin_wipe_player(text, text, text) to anon, authenticated;
grant execute on function public.submit_ban_appeal(text, text) to anon, authenticated;
grant execute on function public.delete_player_account(text, text) to anon, authenticated;
grant execute on function public.send_friend_request(text, text) to anon, authenticated;
grant execute on function public.respond_friend_request(text, bigint, boolean) to anon, authenticated;
grant execute on function public.send_direct_message(text, text, text) to anon, authenticated;
grant execute on function public.mark_notifications_read(text) to anon, authenticated;
grant execute on function public.list_social_state(text) to anon, authenticated;
grant execute on function public.get_infinite_craft_save(text) to anon, authenticated;
grant execute on function public.save_infinite_craft(text, jsonb) to anon, authenticated;
grant execute on function public.delete_infinite_craft_save(text) to anon, authenticated;
grant execute on function public.get_clicker_leaderboard() to anon, authenticated;
grant execute on function public.submit_suggestion(text, text) to anon, authenticated;

with applied_update as (
  insert into public.game_updates(id)
  values ('67-balance-2026-05-13')
  on conflict (id) do nothing
  returning id
)
delete from public.clicker_saves
where exists (select 1 from applied_update);

create index if not exists player_sessions_player_id_idx on public.player_sessions (player_id);
create index if not exists player_sessions_expires_at_idx on public.player_sessions (expires_at);
create index if not exists clicker_saves_max_points_idx on public.clicker_saves (max_points desc);
create index if not exists infinite_craft_saves_updated_at_idx on public.infinite_craft_saves (updated_at desc);
create index if not exists recipe_cache_updated_at_idx on public.recipe_cache (updated_at desc);
create index if not exists players_banned_at_idx on public.players (banned_at);
create index if not exists admin_actions_created_at_idx on public.admin_actions (created_at desc);
create index if not exists friend_requests_recipient_status_idx on public.friend_requests (recipient_id, status);
create index if not exists friendships_player_a_idx on public.friendships (player_a);
create index if not exists friendships_player_b_idx on public.friendships (player_b);
create index if not exists direct_messages_recipient_idx on public.direct_messages (recipient_id, created_at desc);
create index if not exists direct_messages_sender_idx on public.direct_messages (sender_id, created_at desc);
create index if not exists notifications_player_read_idx on public.notifications (player_id, read_at, created_at desc);
create index if not exists ban_appeals_created_at_idx on public.ban_appeals (created_at desc);

-- Make newly-created RPC functions visible to the browser API immediately.
notify pgrst, 'reload schema';
